### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by AltNico** [AltNico/ha-manager#31]
If the contributors don't have something against it, I would like to mention them on an About page, like in [Flym](https://github.com/FredJul/Flym/blob/master/app/src/main/res/values/not_translatable_strings.xml).
@easyaspi314 
@svetlemodry 
@Arya766

**Comment by svetlemodry** [comment]
Fine for me and thanks.

**Comment by Arya766** [comment]
Its actually nice of you, thanks.
On Jan 1, 2015 9:03 PM, "Jaroslav Lichtblau" <notifications@github.com>
wrote:

Fine for me and thanks.

—
Reply to this email directly or view it on GitHub
<https://github.com/AltNico/ha-manager/issues/31#issuecomment-68492482>.

**Comment by easyaspi314** [comment]
Yes, thanks! I can write one up for you, if you want.

**Comment by AltNico** [comment]
@easyaspi314 No need for this, I already have done it. :D 
661a997282cdcac1121a7a3ea9eef350982c97c6
